### ISSUE TITLE
[Question] Is this project suitable for fast-changing rules?

### ISSUE THREAD

**Issue by felipejfc** [florianl/go-conntrack#19]
Hi!

First, thanks for your work on this tool @florianl!

I have an use case where I'll be deleting like 50~100 rules per second, do you think this lib can do the trick? (if not, any other way of doing that?)

I've tried it and sometimes it's giving me a lot of delay to delete some rules, maybe I'm using it the wrong way... I'm trying it on an ubuntu 18 VM.

Thanks!

**Comment by florianl** [comment]
Hi @felipejfc 
and thanks for your feedback!
I'm not aware of limitations. Can you start profiling [1] your program, to identify the critical path [2]?

[1] https://blog.golang.org/profiling-go-programs
[2] https://medium.com/@rakyll/cpdd-critical-path-driven-development-6c2592fb8ea4

**Comment by florianl** [comment]
Please don't hesitate to reopen this issue/question if needed.
