### ISSUE TITLE
ExampleNfct_RegisterFiltered Unknown message type

### ISSUE THREAD

**Issue by daddylhz** [florianl/go-conntrack#2]
when I test func ExampleNfct_RegisterFiltered, the program print
Unknown message type: 0x00
map[]
is there something wrong with Func RegisterFiltered?

**Comment by daddylhz** [comment]
I find my package is not the newest.
It works well with the newest package.
Thx

**Comment by florianl** [comment]
Thank you for your feedback.
As this is no longer an issue, I close this.
