### ISSUE TITLE
Building a prometheus exporter using this lib

### ISSUE THREAD

**Issue by xocasdashdash** [florianl/go-conntrack#20]
Hi!

Would it me possible to build a tool like this: https://github.com/hiveco/conntrack_exporter using this library? 

I haven't fully checked this project but the hiveco one does everything in this file: https://github.com/hiveco/conntrack_exporter/blob/master/src/connection_table.cc

**Comment by florianl** [comment]
Hello @xocasdashdash 
there is an example [1] on how to get statistics. This might be a good starter.
Cheers,
 Florian

[1] https://godoc.org/github.com/florianl/go-conntrack#example-Nfct-DumpCPUStats

**Comment by xocasdashdash** [comment]
Yeah, I see, just a last question, from what i'm reading this package does not need CGO right? Am I understanding this correctly?

**Comment by florianl** [comment]
yes :) this packages does not have c dependencies.

**Comment by xocasdashdash** [comment]
cool thanks!!
