### ISSUE TITLE
Netlink socket read timeouts

### ISSUE THREAD

**Issue by p-lambert** [florianl/go-conntrack#22]
Hi :wave:
I'm not sure if this behavior is intentional or not so apologize in advance for the confusion. 😅
I noticed users of this library using Go >1.12 [can set a read timeout](https://github.com/florianl/go-conntrack/blob/f722615d96b7599de168de06b002a84afa9ed2da/conntrack_gteq_1.12.go#L29-L33) for the underlying Netlink socket via the `ReadTimeout` configuration option.
However if a socket read operation times out, the polling Go routine will simply terminate and the registered callback will no longer receive data.
I believe these errors should be handled somehow as in
```go
if opError, ok := err.(*netlink.OpError); ok {
	if opError.Timeout() || opError.Temporary() {
		// some backoff logic
		continue
	}
}
```
around https://github.com/florianl/go-conntrack/blob/f722615d96b7599de168de06b002a84afa9ed2da/conntrack.go#L310-L313
or perhaps there should be a way to know that the event stream is no longer being consumed.
Thanks!

**Comment by florianl** [comment]
Thanks for reporting this. I will have a look at it.

**Comment by florianl** [comment]
With https://github.com/florianl/go-conntrack/pull/23 this bug has been fixed. Therefore, I will close this issue. Please don't hesitate to reopen it, if I can help you further on this topic.

Thanks again for reporting this bug!
