### ISSUE TITLE
Notification of Fatal Errors

### ISSUE THREAD

**Issue by eay** [florianl/go-conntrack#24]
I have an application using this library, and when on a heavily stressed system, I get a
'error: netlink receive: recvmsg: no buffer space available' error.
The library can be configured to log it, but I want to receive notification so I can act upon this
information. 
I've appended the patch I'm using to give me what I'm after.  I allow an error channel to be passed in with the Config structure.

diff --git a/conntrack.go b/conntrack.go
index febf035..3cb0d13 100644
--- a/conntrack.go
+++ b/conntrack.go
@@ -341,6 +341,9 @@ func (nfct *Nfct) register(ctx context.Context, t Table, groups NetlinkGroup, fi
 					}
 				}
 				nfct.logger.Printf("receiving error: %v", err)
+				if nfct.errorChan != nil {
+					nfct.errorChan <- err
+				}
 				return
 			}
 
diff --git a/conntrack_gteq_1.12.go b/conntrack_gteq_1.12.go
index f5bdba4..6d098a3 100644
--- a/conntrack_gteq_1.12.go
+++ b/conntrack_gteq_1.12.go
@@ -44,5 +44,9 @@ func Open(config *Config) (*Nfct, error) {
 		nfct.setWriteTimeout = func() error { return nil }
 	}
 
+	if config.Error != nil {
+		nfct.errorChan = config.Error
+	}
+
 	return &nfct, nil
 }
diff --git a/conntrack_lt_1.12.go b/conntrack_lt_1.12.go
index 37f3b3a..5e30728 100644
--- a/conntrack_lt_1.12.go
+++ b/conntrack_lt_1.12.go
@@ -28,5 +28,9 @@ func Open(config *Config) (*Nfct, error) {
 	nfct.setReadTimeout = func() error { return nil }
 	nfct.setWriteTimeout = func() error { return nil }
 
+	if config.Error != nil {
+		nfct.errorChan = config.Error
+	}
+
 	return &nfct, nil
 }
diff --git a/types.go b/types.go
index de46107..69b51ab 100644
--- a/types.go
+++ b/types.go
@@ -24,6 +24,9 @@ type Config struct {
 	// Time till a write action times out - only available for Go >= 1.12
 	WriteTimeout time.Duration
 
+	// If there is an error while using a handler (Register), the error
+	// that closed the reader routine will be sent on this channel
+	Error chan error
 	// Interface to log internals.
 	Logger *log.Logger
 }
@@ -35,6 +38,10 @@ type Nfct struct {
 
 	logger *log.Logger
 
+	// If a fatal error occurs, the error will be written to this channel
+	// before the reader go-routine exits
+	errorChan chan error
+
 	setReadTimeout  func() error
 	setWriteTimeout func() error
 }

**Comment by eay** [comment]
When I'm running on a very heavily loaded VM (think of it as stress testing), I end up with over 15000 conntrack entries in the kernel.  On another bare metal box, conntrack -L was reporting
upto 45000 entries.  My program is monitoring this, but is a background task, so if
the conntrack monitoring shuts down, I need to report it (or try to restart).

I'm occasionally seeing the 'no buffer space available'.  I'm getting callbacks from Register() but also doing periodic Dump()s - which does catch some flows that were not reported as dead.
When I do get this error, I'm upping the nfct.Con.SetReadBuffer() and restarting.  The main problem I was having was that things just silently stopped working. It is nice to be able to do a graceful shutdown (if not a restart) by a channel notification instead of monitoring the
log.
I have a hard time reproducing the error, but will get one every few minutes on my test systems.

And yes, I saw 6eba3c1 which was why I was a little aggrieved that fatal errors could not be acted upon :-)

**Comment by florianl** [comment]
Thank you for the feedback.
If I understand you correctly, you just restart everything regardless of the received error. Is this correct?
`no buffer space available` is a quite common problem with the kernel part of the conntrack system and can not be solved by the user space side. So I assume you already modified and checked `ip_conntrack_max`.

**Comment by florianl** [comment]
There is now a function that wil get you the error channel:

https://github.com/florianl/go-conntrack/blob/d487fc80635a7fbb52c166b046a2b45140299cc5/conntrack.go#L300-L311

Hope this helps.

**Comment by eay** [comment]
Thanks, that does just what I needed.  I do restart after making /proc/sys/net/core/rmem_max larger and this seems to help.
Normally my program gets the error when I'm shutting down a large docker cluster (40,000 open connections).  It seems to push it over the edge, but when I restart, things are stable.

**Comment by florianl** [comment]
Thanks for the feedback. Therefore I will close this issue.
