### ISSUE TITLE
Please expose the netlink.Config.DisableNSLockThread option for configuration

### ISSUE THREAD

**Issue by eay** [florianl/go-conntrack#26]
I continue to develop my monitoring program using your library, and my rather pathological test case, which is the current release of the
edgex package, fires up about 18 docker containers that then proceed to furiously talk to each other (50,000 active
network connections).
I hit an interesting situation where my program would sit on about 40% CPU while monitoring; a large amount of the 
processes CPU time being in runtime.futex (35%) and  runtime.findrunnable (%18), which, is to my understanding are locking/scheduling related.  I have 7-8 quite active go-routines running, on a quad core box.
I shutdown the docker containers, which normally triggered a failure on go-conntrack, which I then restarted.
I then restart the containers.  My program now sat on about %20 CPU and those functions would drop to nearly nothing.
If I started my program before starting edgex, it would also be well behaved.
Looking at the different run profiles, I found that after restarting go-conntrack, I was not shutting down the worker go-routine so I had two sitting around.
To me I suspect this is related to the underlying netlink library thread locking its go-routine to clear up issues around
the setNS system call operating on a thread basis.  I'm using setNS (and sock_diag) elsewhere, and I can appreciate
why you would want to lock your go-routine to a real thread.  In my case I setNS, open a socket, then setNS back.
For me this seems to work (the socket is in the alternative namespace and I can keep on talking to it).

When I modified the arguments to netlink to set DisableNSLockThread to true, my problems seemed to go away.
I know what I'm doing elsewhere with setNS and am will to take the chance  with turning this option on.
My problem is the go-conntrack library does not expose this option.  Could I request you add it to you
conntrack.Config structure and pass it through.
I believe I'm seeing a 'semi-random' go-routine scheduling issue because a very active go-routine is being thread locked.

thanks

**Comment by florianl** [comment]
Hi and thanks for the feedback!

Do you have a flamegraph or profile to share, that shows the issue? How did you collect the numbers you mentioned? Would be great to have a minimal code example that reproduces the issue.

**Comment by eay** [comment]
I’ve attached 2 flame graphs, 10 is the bad behaviour, 11 is the good, with DisabledNSLockThread: true
Since they are both just images, and the full details are not captured, here is some more info.
The 3 lines are log entries of rusage from the running program, the CPU etc for the last minute.
The 3 detail lines are from the flame graph, the numbers for the second row.  The drop in system time is also very significant.

If you want

10
total 20.69s
2020/07/06 06:21:31 STATS: %CPUtime=43.0 %Sys=15.6 %user=27.3 MaxRSS=100348 Nv=25323.8 Niv=2327.2
2020/07/06 06:22:31 STATS: %CPUtime=42.2 %Sys=17.9 %user=24.2 MaxRSS=135776 Nv=28760.6 Niv=2462.5
2020/07/06 06:23:31 STATS: %CPUtime=42.3 %Sys=17.8 %user=24.6 MaxRSS=139720 Nv=29032.6 Niv=2450.4
Total 20.69
go-conntrack.(*Nfct).register.func1 23.39% 4.84s
netlin.newLockedNetNSGoroutine.func1 17.88% 3.70s
runtime.mcall 42.82% 8.86s

11
Total 10.51s
2020/07/06 09:25:46 STATS: %CPUtime=24.0 %Sys= 7.8 %user=16.1 MaxRSS=142684 Nv=7920.1 Niv=487.4
2020/07/06 09:26:46 STATS: %CPUtime=24.0 %Sys= 7.9 %user=16.1 MaxRSS=142684 Nv=7898.7 Niv=478.9
2020/07/06 09:27:46 STATS: %CPUtime=24.9 %Sys= 8.1 %user=16.8 MaxRSS=146120 Nv=8042.5 Niv=484.7
go-conntrack.(*Nfct).register.func1 19.12% 3.06s
netlin.newLockedNetNSGoroutine.func1 19.22% 2.02s
runtime.mcall 21.60% 2.27s

eric

**Comment by eay** [comment]
I you wish to run the test case I use, I’ve attached the docker-compose.yml for the edgex release I’m using.  It has something wrong with it,
so there are way too many very short duration tcp connections, but it is a good stress test.

eric

**Comment by florianl** [comment]
With https://github.com/florianl/go-conntrack/commit/60f4fb5fb12a1b4b3a32e4b596056524191c6c27 I've exposed `DisableNSLockThread`.

**Comment by eay** [comment]
Thanks
