### ISSUE TITLE
Deletion of git tags

### ISSUE THREAD

**Issue by florianl** [florianl/go-conntrack#27]
Currently, this project has three different git tags 

- [v3.0.0](https://github.com/florianl/go-conntrack/releases/tag/v3.0.0)
- [v2.0.0](https://github.com/florianl/go-conntrack/releases/tag/v2.0.0)
- [v0.1.0](https://github.com/florianl/go-conntrack/releases/tag/v0.1.0)

All three of them are not reflected in https://github.com/florianl/go-conntrack/blob/master/go.mod and vice versa. In addtion, this leads to confusion for some users - see https://github.com/florianl/go-conntrack/issues/25.

As most users of this pkg are using go modules, I will delete these git tags to reduce confusion in the future.

Therefore, on **September 1st 2020** I will delete the git tags.

If there are concerns with the removal of these git tags, please speak up.

**Comment by florianl** [comment]
After some learning and discussion, I will not delete existing tags but add a new version tag and adapt the Go modules part.

**Comment by RandoMan70** [comment]
@florianl , nice to see that you're working on it! I just bumped to issue that go forbids me to import v3 version as a module due to missing /v3/  path. It would be nice if you, highlight me here as soon as it's done!
