### ISSUE TITLE
Problem with negative filters

### ISSUE THREAD

**Issue by dvomartin** [florianl/go-conntrack#46]
Hi,
I really like this library and I would like to use it in my project, but I found a problem which is kind of show stopper for me.
I have a server with a lot of traffic, but I need to analyse small portion of it.

So I wanted to use RegisterFiltered method for filtration of traffic which is irrelevant for me. But I can't make it work.

I have created filters to remove traffic going from/to localhost in this example:

```
package main

import (
	"context"
	"github.com/florianl/go-conntrack"
	"log"
	"os"
	"time"
)

func main() {
	var err error

	logger := log.Logger{}
	logger.SetOutput(os.Stdout)

	nfct, err := conntrack.Open(&conntrack.Config{
		Logger:                  &logger,
		AddConntrackInformation: true,
	})
	if err != nil {
		logger.Fatalln("could not create nfct: %v", err)
	}

	var processor = func(c conntrack.Con) int {
		if c.Origin.Proto.DstPort == nil {
			logger.Printf("Port for %s is nil\n", c.Origin.Dst.String())
			return 0
		}

		logger.Printf("Conntrack connection: src: %s - dest: %s:%d\n", c.Origin.Src.String(), c.Origin.Dst.String(), *c.Origin.Proto.DstPort)
		return 0
	}

	filters := make([]conntrack.ConnAttr, 0)

	filterLocalhostSrc := conntrack.ConnAttr{Type: conntrack.AttrOrigIPv4Src, Data: []byte{0x7f, 0x0, 0x0, 0x1}, Mask: []byte{0xff, 0xff, 0xff, 0xff}, Negate: true}
	filterLocalhostDst := conntrack.ConnAttr{Type: conntrack.AttrOrigIPv4Dst, Data: []byte{0x7f, 0x0, 0x0, 0x1}, Mask: []byte{0xff, 0xff, 0xff, 0xff}, Negate: true}

	filters = append(filters, filterLocalhostSrc, filterLocalhostDst)

	err = nfct.RegisterFiltered(context.Background(), conntrack.Conntrack, conntrack.NetlinkCtNew|conntrack.NetlinkCtUpdate|conntrack.NetlinkCtDestroy, filters, processor)

	if err != nil {
		logger.Printf("could not register callback: %v\n", err)
	}

	time.Sleep(2 * time.Second)

	err = nfct.Close()
	if err != nil {
		logger.Printf("nfct close error: %v\n", err)
	}

	time.Sleep(1 * time.Second)

	logger.Println("closing")
}

```

But it doesn't work for me. This traffic is still forwarder to the userspace. Example from console:
```
Conntrack connection: src: 127.0.0.1 - dest: 127.0.0.1:8125
Conntrack connection: src: 127.0.0.1 - dest: 127.0.0.1:8125
Conntrack connection: src: 127.0.0.1 - dest: 127.0.0.1:55586
```

I noticed that following error is produced when I call the Close method:
```
receiving error: netlink receive: use of closed file
could not remove filter: netlink remove-bpf: setsockopt: bad file descriptor
could not unsubscribe from group: netlink leave-group: setsockopt: bad file descriptor
```
But I'm not sure if it is relevant.

I have also noticed that if I use positive filter (for example to get just traffic from localhost}, it seems that it works:
```
filterLocalhostSrc := conntrack.ConnAttr{Type: conntrack.AttrOrigIPv4Src, Data: []byte{0x7f, 0x0, 0x0, 0x1}, Mask: []byte{0xff, 0xff, 0xff, 0xff}, Negate: false}
```
So probably just negative filters don't work.

Any suggestion would be appreciated.

Thank you,
Martin

**Comment by florianl** [comment]
Hi dvomartin
And thanks for your feedback.
From the top of my head I can't name the reason for your report. Therefore, it will take some time to dig into it.

**Comment by florianl** [comment]
With https://github.com/florianl/go-conntrack/pull/47 the errors got fixed when calling `Close()`.
The issue was, that the expected order of turn down actions was different. In the example, `context.Background()` was used as argument to `RegisterFiltered(...)`. Before the fix, thix context alone was responsible for the shutdown. With `context.Background()` this context never was canceled and therefore the order of turn down was different than expected.

**Comment by dvomartin** [comment]
Hi @florianl,
thanks for the update. It's great to see a project with active community.

**Comment by dvomartin** [comment]
Hi @florianl,
did you have a change to validate the issue with negative filters? 

I think I found one more problem.

According to documentation of the  RegisterFiltered method, it should be possible to link filters of the same type with OR statement.

But, if I create filter to watch SMTP ports (25, 465 and 587), it doesn't work.
Only connections from the last filter of the same type are being forwarded to the userspace.

```
filterSmtpPort1 := conntrack.ConnAttr{Type: conntrack.AttrOrigPortDst, Data: []byte{0, 25}}
filterSmtpPort2 := conntrack.ConnAttr{Type: conntrack.AttrOrigPortDst, Data: []byte{1, 209}}
filterSmtpPort3 := conntrack.ConnAttr{Type: conntrack.AttrOrigPortDst, Data: []byte{2, 75}}
```

I will try to investigate it myself, but I have no experience with BPF and I have only Mac with M1 cpu, so I will have to find a way how to debug it on my machine.

**Comment by dvomartin** [comment]
Sure, I understand that it might be difficult to find the problem.

**Comment by dvomartin** [comment]
Hi @florianl,
I think I have a fix for the problem with negative filters. It looks fine according to my testing.
Please check my pull request.

**Comment by florianl** [comment]
Fix got merged with https://github.com/florianl/go-conntrack/pull/49. Therefore closing this issue.
