### ISSUE TITLE
Issue around Delete events having zero content.

### ISSUE THREAD

**Issue by eay** [florianl/go-conntrack#6]
I've already responded on the other issue as to why Delete events were not registering, and I believe I have to solution as to why there is zero data.

In conntrack.go,

```
      func parseConnectionMsg(msg netlink.Message, reqType int) (Conn, error) {
           if msg.Header.Type&netlink.Error == netlink.Error {
```

should be

`      if msg.Header.Type == netlink.Error {`

from the relevant linux header
```
     #define NLMSG_NOOP              0x1     /* Nothing.             */
     #define NLMSG_ERROR             0x2     /* Error                */
     #define NLMSG_DONE              0x3     /* End of a dump        */
     #define NLMSG_OVERRUN           0x4     /* Data lost            */
```

The current code does a bitmask on the Header.Type (uint16) with netlink.Error.
When a normal event comes in, it is 0x0100, so all is good. For delete, it is 0x0102, which is causing the code to bail and not decode.  My reading of the headers is that it is a full 16bits, of numbers, not bitmap.  Note that LMSG_DONE would also trigger your error condition.

`#define NLMSG_MIN_TYPE          0x10    /* < 0x10: reserved control messages */`

So anything above that should be ok.  In a few places, you mask the reqType before making the call to parseConnectionMsg().
From netfilter/nfnetlink.h
```
/* netfilter netlink message types are split in two pieces:
 * 8 bit subsystem, 8bit operation.
 */
#define NFNL_SUBSYS_ID(x)       ((x & 0xff00) >> 8)
#define NFNL_MSG_TYPE(x)        (x & 0x00ff)
#define NFNL_SUBSYS_CTNETLINK 1
```
The SUBSYS is NFNL_SUBSYS_CTNETLINK, but I'm not sure what the MSG_TYPES are otherwise.  I'm rather new to netlink/conntrack, but I'm reasonably sure this is why the events are not being decoded when they should be. I'm also not sure what would get broken with these changes

**Comment by florianl** [comment]
Thank you for your feedback. I will have a closer look at this and report back!

**Comment by florianl** [comment]
Update:
Thank you again for your detailed report!
First test showed, I can reproduce the issue. And you pointed me to the correct place.
I've mixed up NFNLGRP_CONNTRACK_DESTROY (0x3) with NF_NETLINK_CONNTRACK_DESTROY (0x4).
A PR will follow.

**Comment by eay** [comment]
Having looked at the fix you have for issue #4, I don't think it will fix the problem with zero items being decoded for DESTROY.  This is my patch to fix that issue (line numbers are off a bit).
The masking for decode needs to occur after the error check and the check has to be a number compare, not a bit compare.

```
diff --git a/conntrack.go b/conntrack.go
index 0da6a8d..8dfe7d1 100644
--- a/conntrack.go
+++ b/conntrack.go
@@ -339,7 +340,7 @@ func (nfct *Nfct) register(ctx context.Context, t CtTable, groups NetlinkGroup,
                        }

                        for _, msg := range reply {
-                               c, err := parseConnectionMsg(msg, int(msg.Header.Type)&0xF)
+                               c, err := parseConnectionMsg(msg, int(msg.Header.Type))
                                if err != nil {
                                        nfct.logger.Printf("could not parse received message: %v", err)
                                }
@@ -454,7 +459,7 @@ func (nfct *Nfct) query(req netlink.Message) ([]Conn, error) {

        var conn []Conn
        for _, msg := range reply {
-               c, err := parseConnectionMsg(msg, int(req.Header.Type)&0xF)
+               c, err := parseConnectionMsg(msg, int(req.Header.Type))
                if err != nil {
                        return nil, err
                }
@@ -476,7 +481,7 @@ func putExtraHeader(familiy, version uint8, resid uint16) []byte {
 type extractFunc func([]byte) (Conn, error)

 func parseConnectionMsg(msg netlink.Message, reqType int) (Conn, error) {
-       if msg.Header.Type&netlink.Error == netlink.Error {
+       if msg.Header.Type == netlink.Error {
                errMsg, err := unmarschalErrMsg(msg.Data)
                if err != nil {
                        return nil, err
@@ -495,7 +500,7 @@ func parseConnectionMsg(msg netlink.Message, reqType int) (Conn, error) {
                ipctnlMsgCtGetStatsCPU: extractStatsCPU,
        }

-       if fn, ok := fnMap[reqType]; ok {
+       if fn, ok := fnMap[reqType&0x0f]; ok {
                return fn(msg.Data)
        }

```

**Comment by florianl** [comment]
If I read it correctly, with your changes, you should get error messages coming from  https://github.com/florianl/go-conntrack/blob/master/conntrack.go#L502 - can you share them?

What kind of information in `Header.Type` do you get, which is not covered by `0xF`?
Reading the kernel Code and the documentation of the underlying netlink library [1], I expect to receive a maximum value of `0x4`.

[1] https://godoc.org/github.com/mdlayher/netlink#HeaderType

**Comment by eay** [comment]
ok, putting the code back to your original, with a 
`fmt.Printf("mht = %d reqType = %d\n", msg.Header.Type, reqType)`
just before your 
`if msg.Header.Type&netlink.Error == netlink.Error {`
line, my program gives

`mht = 258 reqType = 2`

The ErrMsg value that is decoded reads as
```
(conntrack.ErrMsg) {
 Code: (int) 2,
 Len: (uint32) 2147549236,
 Type: (uint16) 20,
 Flags: (uint16) 32769,
 Seq: (uint32) 65544,
 Pid: (uint32) 16777343
}
```
Which definitly looks bad.  If I change the error check to 
`if msg.Header.Type == netlink.Error {`

The de-code that I get and print has valid values
```
1562820010.067553     [NEW] icmp     1 30 src=10.0.2.15 dst=8.8.8.8 type=8 code=0 id=17583 [UNREPLIED] id=2064279424
1562820185.940045 [DESTROY] icmp     1 src=10.0.2.15 dst=8.8.8.8 type=8 code=0 id=17583 send(134,11256) recv(0,0) delta-time=176 id=2064279424
```

Reading https://www.infradead.org/~tgr/libnl/doc/core.html#core_msg_types, it appears that the max value of 4 is just for pre-defined header types.

**Comment by florianl** [comment]
As there is no update in this report, I will close it.
Please don't hesitate to reopen it if needed.
